version: '2'
services:
  clima-db:
    image: 'arm32v7/influxdb:1.7.10'
    container_name: 'clima-db'
    environment:
      - INFLUXDB_DB=climalink
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secretadmin
      - INFLUXDB_USER=climalink
      - INFLUXDB_USER_PASSWORD=secretuser
    volumes:
      - ./data:/var/lib/influx.db
    ports:
      - '8086:8086'
    networks: 
      - clim-network
  clima-storage:
    image: 'pkalkman/clima-storage:0.5.6'
    container_name: 'clima-storage'
    environment:
      - MQTT_BROKER_HOST=clima-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_USERNAME=brokerusername
      - MQTT_PASSWORD=brokerpassword
      - DATABASE_HOST=clima-db
      - DATABASE_NAME=climalink
      - DATABASE_USER=climalink
      - DATABASE_PASSWORD=secretuser
    networks: 
      - clim-network
  clima-broker:
    image: 'pkalkman/clima-broker:0.5.6'
    container_name: 'clima-broker'
    environment:
      - MQTT_BROKER_PORT=8883
      - MQTT_USERNAME=brokerusername
      - MQTT_PASSWORD=brokerpassword
    networks:
      - clim-network
  clima-measure: 
    image: 'pkalkman/clima-measure:0.5.6'
    container_name: 'clima-measure'
    environment:
      - MQTT_BROKER_HOST=clima-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_USERNAME=brokerusername
      - MQTT_PASSWORD=brokerpassword
      - NODE_ENV=production
    networks: 
      - clim-network
networks:
    clim-network: